"""This file is autogenerated by generate_ast.py
do not modify manually the content."""

from dataclasses import dataclass


class ExpressionBase:
    pass


@dataclass
class LiteralExpr(ExpressionBase):
    value: "object"

    def accept(self, visitor):
        return visitor.visit_literal_expr(self)


@dataclass
class UnaryExpr(ExpressionBase):
    token: "Token"
    expr: "ExpressionBase"

    def accept(self, visitor):
        return visitor.visit_unary_expr(self)


@dataclass
class BinaryExpr(ExpressionBase):
    left: "ExpressionBase"
    token: "Token"
    right: "ExpressionBase"

    def accept(self, visitor):
        return visitor.visit_binary_expr(self)


@dataclass
class LogicalExpr(ExpressionBase):
    left: "ExpressionBase"
    token: "Token"
    right: "ExpressionBase"

    def accept(self, visitor):
        return visitor.visit_logical_expr(self)


@dataclass
class AssignmentExpr(ExpressionBase):
    name: "Token"
    value: "ExpressionBase"

    def accept(self, visitor):
        return visitor.visit_assignment_expr(self)


@dataclass
class GroupingExpr(ExpressionBase):
    expr: "ExpressionBase"

    def accept(self, visitor):
        return visitor.visit_grouping_expr(self)


@dataclass
class VariableExpr(ExpressionBase):
    name: "Token"

    def accept(self, visitor):
        return visitor.visit_variable_expr(self)
