"""
This module defines custom exceptions for error handling
in the lox interpreter.
"""

from dataclasses import dataclass
import logging
import sys
from typing import List

from scanner.token_type import TokenType
from scanner.token import Token


@dataclass
class ScannerError(Exception):
    line: int
    message: str

@dataclass
class ParserError(Exception):
    token: Token
    message: str


@dataclass
class RuntimeError(Exception):
    token: Token
    message: str


@dataclass
class ErrorHandler:
    """Class for handling errors throughout the lox interpreter lifespan.

    Attributes:
        errors: List[ParserError]
            List of errors generated by the parser component.
        runtimeError:
            Error generated at runtime
    """

    def __init__(self):
        self.errors: List[ParserError] = []
        self.runtime_error: RuntimeError = None

    def report_errors(self):
        for e in self.errors:
            if isinstance(e, ScannerError):
                print(f'[line {str(e.line)}] Error: {e.message}', file=sys.stderr)
            elif e.token.token_type == TokenType.EOF:
                print(f'[line {str(e.token.line)}] Error at end: {e.message}', file=sys.stderr)
            else:
                print(
                    f'[line {str(e.token.line)}] Error at \'{e.token.lexeme}\': {e.message}',
                    file=sys.stderr
                )

    def report_runtime_error(self):
        """Reports a runtime error for a given operator."""
        print(
            f"{self.runtime_error.message}", file=sys.stderr
        )
        print(
            f"[line {self.runtime_error.token.line}] in script", file=sys.stderr
        )
