"""
This module defines custom exceptions for error handling
in the lox interpreter.
"""

from dataclasses import dataclass
import logging
from typing import List

from scanner.token_type import TokenType
from scanner.token import Token


@dataclass
class ParserError(Exception):
    token: Token
    message: str


@dataclass
class RuntimeError(Exception):
    token: Token
    message: str


@dataclass
class ErrorHandler:
    """Class for handling errors throughout the lox interpreter lifespan.

    Attributes:
        errors: List[ParserError]
            List of errors generated by the parser component.
        runtimeError:
            Error generated at runtime
    """

    def __init__(self):
        self.errors: List[ParserError] = []
        self.runtime_error: RuntimeError = None

    def report_errors(self):
        for e in self.errors:
            if e.token.token_type == TokenType.EOF:
                logging.error(str(e.token.line) + " at end: " + e.message)
            else:
                logging.error(
                    str(e.token.line)
                    + " at "
                    + e.token.lexeme
                    + ": "
                    + e.message
                )

    def report_runtime_error(self):
        """Reports a runtime error for a given operator."""
        logging.error(
            self.runtime_error.message + f" {self.runtime_error.token}"
        )
